# Site wide configuration

title:            omxi.se
locale:           en_US
url:              http://www.omxi.se
teaser: teaser.jpg

# Jekyll configure
permalink:   :year-:month-:day-:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Rake

editor: vim
git:
  branch: master
  branch_dev: dev
transfer:
  command: rsync
  settings: -havz --delete
  source: _site/
  destination: monki@omxi.se:www/omxi.se/www/
  destination_dev: monki@omxi.se:www/dev.omxi.se/www/

# Site owner
owner:
  name: Magnus Eriksson
  avatar: bio-photo.jpg
  bio: "Internet and beyond. Pre-modern, post-human, para-academic."
  email: ok@omxi.se
  disqus-shortname: blay 
  twitter: monki #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: omxi #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  zotero: magnu.se #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
